### ISSUE TITLE
Fail cap production deploy

### ISSUE THREAD

**Issue by ysakasin** [ysakasin/proconist.net#73]
## All logs
```
[Deprecation Notice] Future versions of Capistrano will not load the Git SCM
plugin by default. To silence this deprecation warning, add the following to
your Capfile after `require "capistrano/deploy"`:

    require "capistrano/scm/git"
    install_plugin Capistrano::SCM::Git

00:00 rbenv:validate
      rbenv: rbenv_ruby is not set; ruby version will be defined by the remote hosts via rbenv
00:00 git:wrapper
      01 mkdir -p /tmp
Enter passphrase for /Users/sinji/.ssh/id_rsa:
    ✔ 01 deploy@proconist.net 4.074s
      Uploading /tmp/git-ssh-proconist.net-production-sinji.sh 100.0%
      02 chmod 700 /tmp/git-ssh-proconist.net-production-sinji.sh
    ✔ 02 deploy@proconist.net 0.138s
Please enter branch (master): master
00:10 git:check
      01 git ls-remote git@github.com:NKMR6194/proconist.net.git HEAD
      01 b89f5c3feecfa61f8348180f091e17843747c9ee	HEAD
    ✔ 01 deploy@proconist.net 2.384s
00:13 deploy:check:directories
      01 mkdir -p /var/www/proconist.net/shared /var/www/proconist.net/releases
    ✔ 01 deploy@proconist.net 0.137s
00:13 deploy:check:linked_dirs
      01 mkdir -p /var/www/proconist.net/shared/log /var/www/proconist.net/shared/tmp/pids /var/www/proconist.net/share…
    ✔ 01 deploy@proconist.net 0.161s
00:13 git:clone
      The repository mirror is at /var/www/proconist.net/repo
00:14 git:update
      01 git remote set-url origin git@github.com:NKMR6194/proconist.net.git
    ✔ 01 deploy@proconist.net 0.219s
      02 git remote update --prune
      02 Fetching origin
      02 From github.com:NKMR6194/proconist.net
      02    87a26a8..b89f5c3  master     -> master
      02  * [new ref]         refs/pull/67/head -> refs/pull/67/head
      02  * [new ref]         refs/pull/68/head -> refs/pull/68/head
      02  * [new ref]         refs/pull/69/head -> refs/pull/69/head
      02  * [new ref]         refs/pull/70/head -> refs/pull/70/head
      02  * [new ref]         refs/pull/72/head -> refs/pull/72/head
    ✔ 02 deploy@proconist.net 2.903s
00:17 git:create_release
      01 mkdir -p /var/www/proconist.net/releases/20180416140100
    ✔ 01 deploy@proconist.net 0.138s
      02 git archive master | /usr/bin/env tar -x -f - -C /var/www/proconist.net/releases/20180416140100
    ✔ 02 deploy@proconist.net 0.217s
00:18 deploy:set_current_revision
      01 echo "b89f5c3feecfa61f8348180f091e17843747c9ee" > REVISION
    ✔ 01 deploy@proconist.net 0.141s
00:18 deploy:symlink:linked_dirs
      01 mkdir -p /var/www/proconist.net/releases/20180416140100 /var/www/proconist.net/releases/20180416140100/tmp /va…
    ✔ 01 deploy@proconist.net 0.134s
      02 rm -rf /var/www/proconist.net/releases/20180416140100/log
    ✔ 02 deploy@proconist.net 0.134s
      03 ln -s /var/www/proconist.net/shared/log /var/www/proconist.net/releases/20180416140100/log
    ✔ 03 deploy@proconist.net 0.146s
      04 ln -s /var/www/proconist.net/shared/tmp/pids /var/www/proconist.net/releases/20180416140100/tmp/pids
    ✔ 04 deploy@proconist.net 0.134s
      05 ln -s /var/www/proconist.net/shared/tmp/cache /var/www/proconist.net/releases/20180416140100/tmp/cache
    ✔ 05 deploy@proconist.net 0.137s
      06 ln -s /var/www/proconist.net/shared/tmp/sockets /var/www/proconist.net/releases/20180416140100/tmp/sockets
    ✔ 06 deploy@proconist.net 0.149s
      07 ln -s /var/www/proconist.net/shared/public/system /var/www/proconist.net/releases/20180416140100/public/system
    ✔ 07 deploy@proconist.net 0.137s
      08 ln -s /var/www/proconist.net/shared/vendor/bundle /var/www/proconist.net/releases/20180416140100/vendor/bundle
    ✔ 08 deploy@proconist.net 0.135s
      09 ln -s /var/www/proconist.net/shared/public/assets /var/www/proconist.net/releases/20180416140100/public/assets
    ✔ 09 deploy@proconist.net 0.137s
00:22 bundler:install
      01 $HOME/.rbenv/bin/rbenv exec bundle install --path /var/www/proconist.net/shared/bundle --without development t…
    ✔ 01 deploy@proconist.net 133.371s
02:35 deploy:assets:precompile
      01 $HOME/.rbenv/bin/rbenv exec bundle exec rake assets:precompile
      01 I, [2018-04-16T23:03:37.356756 #6850]  INFO -- : Writing /var/www/proconist.net/releases/20180416140100/public…
      01 I, [2018-04-16T23:03:37.357580 #6850]  INFO -- : Writing /var/www/proconist.net/releases/20180416140100/public…
      01 I, [2018-04-16T23:03:53.084900 #6850]  INFO -- : Writing /var/www/proconist.net/releases/20180416140100/public…
      01 I, [2018-04-16T23:03:53.085504 #6850]  INFO -- : Writing /var/www/proconist.net/releases/20180416140100/public…
    ✔ 01 deploy@proconist.net 30.240s
03:06 deploy:assets:backup_manifest
      01 mkdir -p /var/www/proconist.net/releases/20180416140100/assets_manifest_backup
    ✔ 01 deploy@proconist.net 0.132s
      02 cp /var/www/proconist.net/releases/20180416140100/public/assets/.sprockets-manifest-01ab8b583b9da5b07b450c827a…
    ✔ 02 deploy@proconist.net 0.136s
03:06 deploy:migrate
      [deploy:migrate] Run `rake db:migrate`
03:06 deploy:migrating
      01 $HOME/.rbenv/bin/rbenv exec bundle exec rake db:migrate
    ✔ 01 deploy@proconist.net 3.925s
03:10 deploy:symlink:release
      01 ln -s /var/www/proconist.net/releases/20180416140100 /var/www/proconist.net/releases/current
    ✔ 01 deploy@proconist.net 0.134s
      02 mv /var/www/proconist.net/releases/current /var/www/proconist.net
    ✔ 02 deploy@proconist.net 0.145s
#<Thread:0x00007fbfa6386310@/Users/sinji/.rvm/gems/ruby-2.5.1/gems/sshkit-1.16.0/lib/sshkit/runners/parallel.rb:10 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	1: from /Users/sinji/.rvm/gems/ruby-2.5.1/gems/sshkit-1.16.0/lib/sshkit/runners/parallel.rb:11:in `block (2 levels) in execute'
/Users/sinji/.rvm/gems/ruby-2.5.1/gems/sshkit-1.16.0/lib/sshkit/runners/parallel.rb:15:in `rescue in block (2 levels) in execute': Exception while executing as deploy@proconist.net: Don't know how to build task 'puma:phased-restart' (see --tasks) (SSHKit::Runner::ExecuteError)
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as deploy@proconist.net: Don't know how to build task 'puma:phased-restart' (see --tasks)


Caused by:
Don't know how to build task 'puma:phased-restart' (see --tasks)

Tasks: TOP => deploy:restart
(See full trace by running task with --trace)
The deploy has failed with an error: Exception while executing as deploy@proconist.net: Don't know how to build task 'puma:phased-restart' (see --tasks)


** DEPLOY FAILED
** Refer to log/capistrano.log for details. Here are the last 20 lines:


 DEBUG [044ac9ee] Running /usr/bin/env ls /var/www/proconist.net/releases/20180416140100/public/assets/.sprockets-manifest* as deploy@proconist.net

 DEBUG [044ac9ee] Command: cd /var/www/proconist.net/releases/20180416140100 && ( export RBENV_ROOT="$HOME/.rbenv" RBENV_VERSION="" ; /usr/bin/env ls /var/www/proconist.net/releases/20180416140100/public/assets/.sprockets-manifest* )

 DEBUG [044ac9ee] 	/var/www/proconist.net/releases/20180416140100/public/assets/.sprockets-manifest-01ab8b583b9da5b07b450c827aa7ec8a.json

 DEBUG [044ac9ee] Finished in 0.138 seconds with exit status 0 (successful).

  INFO [cf8d0a48] Running /usr/bin/env cp /var/www/proconist.net/releases/20180416140100/public/assets/.sprockets-manifest-01ab8b583b9da5b07b450c827aa7ec8a.json /var/www/proconist.net/releases/20180416140100/assets_manifest_backup as deploy@proconist.net

 DEBUG [cf8d0a48] Command: cd /var/www/proconist.net/releases/20180416140100 && ( export RBENV_ROOT="$HOME/.rbenv" RBENV_VERSION="" ; /usr/bin/env cp /var/www/proconist.net/releases/20180416140100/public/assets/.sprockets-manifest-01ab8b583b9da5b07b450c827aa7ec8a.json /var/www/proconist.net/releases/20180416140100/assets_manifest_backup )

  INFO [cf8d0a48] Finished in 0.136 seconds with exit status 0 (successful).

  INFO [deploy:migrate] Run `rake db:migrate`

 DEBUG [838d0dbd] Running if test ! -d /var/www/proconist.net/releases/20180416140100; then echo "Directory does not exist '/var/www/proconist.net/releases/20180416140100'" 1>&2; false; fi as deploy@proconist.net

 DEBUG [838d0dbd] Command: if test ! -d /var/www/proconist.net/releases/20180416140100; then echo "Directory does not exist '/var/www/proconist.net/releases/20180416140100'" 1>&2; false; fi

 DEBUG [838d0dbd] Finished in 0.131 seconds with exit status 0 (successful).

  INFO [62fb91d4] Running $HOME/.rbenv/bin/rbenv exec bundle exec rake db:migrate as deploy@proconist.net

 DEBUG [62fb91d4] Command: cd /var/www/proconist.net/releases/20180416140100 && ( export RBENV_ROOT="$HOME/.rbenv" RBENV_VERSION="" RAILS_ENV="production" ; $HOME/.rbenv/bin/rbenv exec bundle exec rake db:migrate )

  INFO [62fb91d4] Finished in 3.925 seconds with exit status 0 (successful).

  INFO [d4b1ac3d] Running /usr/bin/env ln -s /var/www/proconist.net/releases/20180416140100 /var/www/proconist.net/releases/current as deploy@proconist.net

 DEBUG [d4b1ac3d] Command: ( export RBENV_ROOT="$HOME/.rbenv" RBENV_VERSION="" ; /usr/bin/env ln -s /var/www/proconist.net/releases/20180416140100 /var/www/proconist.net/releases/current )

  INFO [d4b1ac3d] Finished in 0.134 seconds with exit status 0 (successful).

  INFO [2956ae4c] Running /usr/bin/env mv /var/www/proconist.net/releases/current /var/www/proconist.net as deploy@proconist.net

 DEBUG [2956ae4c] Command: ( export RBENV_ROOT="$HOME/.rbenv" RBENV_VERSION="" ; /usr/bin/env mv /var/www/proconist.net/releases/current /var/www/proconist.net )

  INFO [2956ae4c] Finished in 0.145 seconds with exit status 0 (successful).
```

**Comment by NKMR6194** [comment]
b2711c9001012caa9c150c432460b154e0c5e630 を試したところ、デプロイは一応できたけどおかしい

```
$ bundle exec cap production deploy
[Deprecation Notice] Future versions of Capistrano will not load the Git SCM
plugin by default. To silence this deprecation warning, add the following to
your Capfile after `require "capistrano/deploy"`:

    require "capistrano/scm/git"
    install_plugin Capistrano::SCM::Git

00:00 rbenv:validate
      rbenv: rbenv_ruby is not set; ruby version will be defined by the remote hosts via rbenv
00:00 git:wrapper
      01 mkdir -p /tmp
Enter passphrase for /Users/sinji/.ssh/id_rsa:
    ✔ 01 deploy@proconist.net 3.835s
      Uploading /tmp/git-ssh-proconist.net-production-sinji.sh 100.0%
      02 chmod 700 /tmp/git-ssh-proconist.net-production-sinji.sh
    ✔ 02 deploy@proconist.net 0.144s
Please enter branch (fix_cap): fix_cap
00:07 git:check
      01 git ls-remote git@github.com:NKMR6194/proconist.net.git HEAD
      01 b89f5c3feecfa61f8348180f091e17843747c9ee	HEAD
    ✔ 01 deploy@proconist.net 2.297s
00:10 deploy:check:directories
      01 mkdir -p /var/www/proconist.net/shared /var/www/proconist.net/releases
    ✔ 01 deploy@proconist.net 0.134s
00:10 deploy:check:linked_dirs
      01 mkdir -p /var/www/proconist.net/shared/log /var/www/proconist.net/shared/tmp/pids /var/www/proconist.net/share…
    ✔ 01 deploy@proconist.net 0.143s
00:10 git:clone
      The repository mirror is at /var/www/proconist.net/repo
00:11 git:update
      01 git remote set-url origin git@github.com:NKMR6194/proconist.net.git
    ✔ 01 deploy@proconist.net 0.146s
      02 git remote update --prune
      02 Fetching origin
      02 From github.com:NKMR6194/proconist.net
      02  * [new branch]      fix_cap    -> fix_cap
    ✔ 02 deploy@proconist.net 2.768s
00:14 git:create_release
      01 mkdir -p /var/www/proconist.net/releases/20180416142308
    ✔ 01 deploy@proconist.net 0.133s
      02 git archive fix_cap | /usr/bin/env tar -x -f - -C /var/www/proconist.net/releases/20180416142308
    ✔ 02 deploy@proconist.net 0.242s
00:14 deploy:set_current_revision
      01 echo "b2711c9001012caa9c150c432460b154e0c5e630" > REVISION
    ✔ 01 deploy@proconist.net 0.140s
00:15 deploy:symlink:linked_dirs
      01 mkdir -p /var/www/proconist.net/releases/20180416142308 /var/www/proconist.net/releases/20180416142308/tmp /va…
    ✔ 01 deploy@proconist.net 0.143s
      02 rm -rf /var/www/proconist.net/releases/20180416142308/log
    ✔ 02 deploy@proconist.net 0.141s
      03 ln -s /var/www/proconist.net/shared/log /var/www/proconist.net/releases/20180416142308/log
    ✔ 03 deploy@proconist.net 0.138s
      04 ln -s /var/www/proconist.net/shared/tmp/pids /var/www/proconist.net/releases/20180416142308/tmp/pids
    ✔ 04 deploy@proconist.net 0.132s
      05 ln -s /var/www/proconist.net/shared/tmp/cache /var/www/proconist.net/releases/20180416142308/tmp/cache
    ✔ 05 deploy@proconist.net 0.132s
      06 ln -s /var/www/proconist.net/shared/tmp/sockets /var/www/proconist.net/releases/20180416142308/tmp/sockets
    ✔ 06 deploy@proconist.net 0.138s
      07 ln -s /var/www/proconist.net/shared/public/system /var/www/proconist.net/releases/20180416142308/public/system
    ✔ 07 deploy@proconist.net 0.131s
      08 ln -s /var/www/proconist.net/shared/vendor/bundle /var/www/proconist.net/releases/20180416142308/vendor/bundle
    ✔ 08 deploy@proconist.net 0.133s
      09 ln -s /var/www/proconist.net/shared/public/assets /var/www/proconist.net/releases/20180416142308/public/assets
    ✔ 09 deploy@proconist.net 0.133s
00:19 bundler:install
      01 $HOME/.rbenv/bin/rbenv exec bundle install --path /var/www/proconist.net/shared/bundle --without development t…
    ✔ 01 deploy@proconist.net 1.299s
00:20 deploy:assets:precompile
      01 $HOME/.rbenv/bin/rbenv exec bundle exec rake assets:precompile
    ✔ 01 deploy@proconist.net 3.141s
00:23 deploy:assets:backup_manifest
      01 mkdir -p /var/www/proconist.net/releases/20180416142308/assets_manifest_backup
    ✔ 01 deploy@proconist.net 0.132s
      02 cp /var/www/proconist.net/releases/20180416142308/public/assets/.sprockets-manifest-01ab8b583b9da5b07b450c827a…
    ✔ 02 deploy@proconist.net 0.131s
00:24 deploy:migrate
      [deploy:migrate] Run `rake db:migrate`
00:24 deploy:migrating
      01 $HOME/.rbenv/bin/rbenv exec bundle exec rake db:migrate
    ✔ 01 deploy@proconist.net 3.109s
00:27 deploy:symlink:release
      01 ln -s /var/www/proconist.net/releases/20180416142308 /var/www/proconist.net/releases/current
    ✔ 01 deploy@proconist.net 0.121s
      02 mv /var/www/proconist.net/releases/current /var/www/proconist.net
    ✔ 02 deploy@proconist.net 0.137s
00:28 puma:phased-restart
      01 $HOME/.rbenv/bin/rbenv exec bundle exec pumactl -S /var/www/proconist.net/shared/tmp/pids/puma.state -F /var/w…
      01 Command phased-restart sent success
    ✔ 01 deploy@proconist.net 0.839s
00:29 deploy:cleanup
      Keeping 5 of 7 deployed releases on proconist.net
      01 rm -rf /var/www/proconist.net/releases/20171009025343 /var/www/proconist.net/releases/20171009060557
    ✔ 01 deploy@proconist.net 0.437s
00:30 deploy:log_revision
      01 echo "Branch fix_cap (at b2711c9001012caa9c150c432460b154e0c5e630) deployed as release 20180416142308 by yasuh…
    ✔ 01 deploy@proconist.net 0.142s
00:30 puma:restart
      01 $HOME/.rbenv/bin/rbenv exec bundle exec pumactl -S /var/www/proconist.net/shared/tmp/pids/puma.state -F /var/w…
      01 Puma starting in single mode...
      01 * Version 3.11.4 (ruby 2.5.1-p57), codename: Love Song
      01 * Min threads: 0, max threads: 16
      01 * Environment: production
      01 * Listening on unix:///var/www/proconist.net/shared/tmp/sockets/puma.sock
      01 Use Ctrl-C to stop
```

ここで止まる。 `Ctrl-C` をしたらデプロイプロセスからは離脱したが、この挙動はおかしい。なお、アプリケーションの切り替えはできていた。

**Comment by ysakasin** [comment]
#75 でRails、Capistranoとサヨナラした
